version: '3.8'
services:
  emqx-enterprise:
    image: emqx/emqx-enterprise:6.0.0
    container_name: emqx
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - 1883:1883
      - 18083:18083

  mqttx-simulate:
    image: emqx/mqttx-cli:latest
    container_name: mqttx-simulate
    command:
      - /bin/sh
      - -c
      - |
        mqttx simulate -sc IEM -c 10 -h emqx-enterprise
    depends_on:
      emqx-enterprise:
        condition: service_healthy

  mqttx:
    image: emqx/mqttx-cli:v1.12.1
    container_name: mqttx
    command:
      - /bin/sh
      - -c
      - |
        mqttx sub -t 'mqttx/simulate/#' -v -h emqx-enterprise
    depends_on:
      emqx-enterprise:
        condition: service_healthy

  emqx-exporter:
    image: emqx/emqx-exporter
    container_name: emqx-exporter
    ports:
      - 8085:8085
    command:
      - '--emqx.nodes=emqx-enterprise:18083'
      - '--emqx.auth-username=admin'
      - '--emqx.auth-password=public'
    depends_on:
      emqx-enterprise:
        condition: service_healthy

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - 5432:5432
    volumes:
      - $PWD/create-table.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=public
      - POSTGRES_DB=iot_data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=public
    volumes:
      - $PWD/emqx-exporter/config/grafana-template/EMQX5-enterprise:/grafana-dashboard-emqx5-ee
      - $PWD/grafana-dashboards:/grafana-dashboard-IEM
      - $PWD/grafana-provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - $PWD/grafana-provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      emqx-enterprise:
        condition: service_healthy
      timescaledb:
        condition: service_started

networks:
  emqx-net:
    name: emqx-net
